### Done concepts:

* Numpy array creation in different dimensions
* Accessing elements from different dimensional arrays.


In [1]:
## shape of the arrays:

import numpy as np


a = np.array([[1,2,3,4],[5,6,7,8]])   ### 2-d array
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [2]:
a.shape ### no_of rows,no_of_columns

(2, 4)

In [4]:
b = np.arange(1,10)    ### 1-d array
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
b.shape  ### no_of_columns

(9,)

In [7]:
c = np.array([[[1,2,3,4],[6,7,8,9]],[[0,6,7,8],[4,5,6,7]]])
c

array([[[1, 2, 3, 4],
        [6, 7, 8, 9]],

       [[0, 6, 7, 8],
        [4, 5, 6, 7]]])

In [8]:
c.shape   ### no_of_2_darrays,no_of_rows,no_of_columns

(2, 2, 4)

### Reshaping of arrays:

* changing the dimensions of the given array.

In [42]:
a = np.array([1,2,3,5,6,7,8])
a.ndim

1

In [12]:
t = a.reshape(7,1)
t

array([[1],
       [2],
       [3],
       [5],
       [6],
       [7],
       [8]])

In [14]:
t.ndim

2

In [15]:
a = np.array([1,2,3,5,6,7,8,9])
a.ndim

1

In [17]:
a.reshape(8,1)

array([[1],
       [2],
       [3],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [18]:
a.reshape(2,4)

array([[1, 2, 3, 5],
       [6, 7, 8, 9]])

In [19]:
a.reshape(4,2)

array([[1, 2],
       [3, 5],
       [6, 7],
       [8, 9]])

In [20]:
a.reshape(1,8)

array([[1, 2, 3, 5, 6, 7, 8, 9]])

In [23]:
a.reshape(1,2,4)

array([[[1, 2, 3, 5],
        [6, 7, 8, 9]]])

In [24]:
a.reshape(2,2,2)

array([[[1, 2],
        [3, 5]],

       [[6, 7],
        [8, 9]]])

In [25]:
a.reshape(4,1,2)

array([[[1, 2]],

       [[3, 5]],

       [[6, 7]],

       [[8, 9]]])

In [27]:
a = np.array([1,2,4,5],ndmin = 5)    ### multidimensional
a

array([[[[[1, 2, 4, 5]]]]])

In [28]:
## ndim ---- checking dimension of an given array.
## ndmin ----- creating array with that particular value.

In [32]:
### for unknown shapes:

a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
a.reshape(2,2,-1)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [35]:
a.reshape(2,-1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [41]:
a = np.array([1,2,3,4,5])
a.reshape(5,-1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [43]:
a

array([1, 2, 3, 5, 6, 7, 8])

In [46]:
a.reshape(7,-1)

array([[1],
       [2],
       [3],
       [5],
       [6],
       [7],
       [8]])

In [49]:
a.reshape(-1,7)

array([[1, 2, 3, 5, 6, 7, 8]])

In [51]:
### at only one place you can give -1(unknown value) but when you gving this you have to check the 
### division of rows and columns exactly.

### Iterating of arrays:



In [52]:
### 1-d array.

a = np.array([1,2,3,4,6,7,8])
a

array([1, 2, 3, 4, 6, 7, 8])

In [58]:
for i in a:
    print(i,end = " ")

1 2 3 4 6 7 8 

In [59]:
### 2-d array:

b = np.array([[1,2,3,5],[6,7,8,9]])
b

array([[1, 2, 3, 5],
       [6, 7, 8, 9]])

In [60]:
for i in b: ### from entire array i will hold each row
    for j in i:  ## from each row you will get each value,those values will be in j.
        print(j,end = " ")

1 2 3 5 6 7 8 9 

In [61]:
### 3-d array:
c

array([[[1, 2, 3, 4],
        [6, 7, 8, 9]],

       [[0, 6, 7, 8],
        [4, 5, 6, 7]]])

In [62]:
for i in c:  #### i will hold each 2-d array.
    for j in i:   #### j will hold each row from i
        for k in j:   ### k will hold each element from j
            print(k,end = " ")
        

1 2 3 4 6 7 8 9 0 6 7 8 4 5 6 7 

In [63]:

### keyword for iterating arrays:

for i in np.nditer(c):
    print(i,end = " ")

1 2 3 4 6 7 8 9 0 6 7 8 4 5 6 7 

In [64]:
for i in np.nditer(b):
    print(i,end = " ")

1 2 3 5 6 7 8 9 

In [66]:
### Joining of arrays:

### 1-d array

a = np.arange(1,9)
b = np.arange(6,11)
c = np.concatenate((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  6,  7,  8,  9, 10])

In [69]:
## 2-d array

c = np.array([[1,2,3,4],[2,3,4,5]])
d = np.array([[1,4,56,7],[4,5,6,7]])

e = np.concatenate((c,d))
e

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 1,  4, 56,  7],
       [ 4,  5,  6,  7]])

In [70]:
a = np.arange(1,11).reshape(2,5)

In [71]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### stastical and math operations on arrays:



In [74]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [75]:
np.min(a)

1

In [76]:
np.max(a)

10

In [77]:
np.mean(a)

5.5

In [78]:
np.std(a)

2.8722813232690143

In [79]:
np.var(a)

8.25

In [80]:
np.median(a)

5.5

In [81]:
np.average(a)

5.5

In [82]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [83]:
np.average(a,0)  ### 0----- columns

array([3.5, 4.5, 5.5, 6.5, 7.5])

In [84]:
np.average(a,1)   ### 1---- row

array([3., 8.])

In [87]:
np.hstack(a)   ### horizantal stack

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
np.vstack(a)   ###vertical stack

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [90]:
a.sum()

55

In [91]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766]])

In [92]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04]])

In [93]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111]])

In [94]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153]])

In [95]:
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501],
       [-0.29100619,  0.87144798, -6.79971146, -0.45231566,  0.64836083]])

In [96]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509]])

In [97]:
np.remainder(a,1)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [99]:
np.degrees(a)

array([[ 57.29577951, 114.59155903, 171.88733854, 229.18311805,
        286.47889757],
       [343.77467708, 401.07045659, 458.3662361 , 515.66201562,
        572.95779513]])

In [101]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [102]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

### Flatten and Ravel:

* Ravel : if you create a new array using ravel and made changes in that new array,the changes will be applied in  the original array.

* Flatten : if you create a new array using flatten and made changes in new array,those modifications won't apply in original array.



In [104]:
a = np.array([[1,2,3,4],[3,2,4,1]])
print(a.ravel())

[1 2 3 4 3 2 4 1]


In [105]:
print(a.flatten())

[1 2 3 4 3 2 4 1]


In [107]:
b = a.ravel()
b

array([1, 2, 3, 4, 3, 2, 4, 1])

In [108]:
b[0] = 10

In [109]:
b

array([10,  2,  3,  4,  3,  2,  4,  1])

In [110]:
a

array([[10,  2,  3,  4],
       [ 3,  2,  4,  1]])

In [111]:
a

array([[10,  2,  3,  4],
       [ 3,  2,  4,  1]])

In [112]:
c = a.flatten()
c

array([10,  2,  3,  4,  3,  2,  4,  1])

In [113]:
c[0] = 11

In [114]:
c

array([11,  2,  3,  4,  3,  2,  4,  1])

In [115]:
a

array([[10,  2,  3,  4],
       [ 3,  2,  4,  1]])