## Numpy:

In [1]:
### Installation of Numpy:



In [2]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [3]:
### importing the numpy:

import numpy as np

### Creating the Arrays :



In [4]:
### 1-d array:

a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [5]:
a.dtype

dtype('int32')

In [6]:
a = np.array(['q',1,2,3,4])

In [7]:
a.dtype  ## checking the data type of the array .

dtype('<U1')

In [14]:
a = np.append(a,1)  ## appending elements in the array
a

array(['q', '1', '2', '3', '4', '1', '1', '1', '1', '1', '1'],
      dtype='<U11')

In [15]:
a = np.arange(0,10) ### range of values 

In [16]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a = np.arange(0,10,2)   ### rannge with step value.
a

array([0, 2, 4, 6, 8])

In [24]:
a.nbytes ### checking the memeory occuiped

20

In [25]:
a.itemsize ### checking the size of each element.

4

In [27]:
len(a)  ### checking the length of the array.


5

In [29]:
np.linspace(1,10,20)  ### dividing the given range with equal difference between each element.

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [31]:
np.full(10,'Python') ### repating the given value in defined number of times.

array(['Python', 'Python', 'Python', 'Python', 'Python', 'Python',
       'Python', 'Python', 'Python', 'Python'], dtype='<U6')

In [33]:
np.ones(10) ### reapeting 1's defined number of times.

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
np.ones(10,dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [38]:
np.full(10,2)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [39]:
np.zeros(10)  ### repeating the 0's defined number of times

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [42]:
np.full(10,'1,2')

array(['1,2', '1,2', '1,2', '1,2', '1,2', '1,2', '1,2', '1,2', '1,2',
       '1,2'], dtype='<U3')

In [43]:
### 2-d array:  combination of more 1-d arrays

b = np.array([[1,2,3,4],[5,6,7,8]])
b


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [44]:
b.dtype

dtype('int32')

In [45]:
b.nbytes

32

In [46]:
b.itemsize

4

In [47]:
b.ndim

2

In [48]:
a.ndim

1

In [49]:
len(b)    ### number of rows present in the array.

2

In [50]:
#### 3-d array : combination of  more 2-d arrays

c = np.array([[[1,2,3,4],[1,2,3,4]],[[5,6,7,8],[9,8,7,6]]])
c

array([[[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[5, 6, 7, 8],
        [9, 8, 7, 6]]])

In [51]:
len(c)

2

In [52]:
c.ndim

3

In [53]:
c.nbytes

64

In [54]:
c.itemsize

4

In [57]:
### Multi dimensional array:

d = np.array([1,2,3,4],ndmin = 10)
d

array([[[[[[[[[[1, 2, 3, 4]]]]]]]]]])

In [58]:
d = np.array([[1,2,3,4],[4,5,6,7]],ndmin = 10)
d

array([[[[[[[[[[1, 2, 3, 4],
               [4, 5, 6, 7]]]]]]]]]])

In [59]:
d.ndim

10

## Accessing the elements

In [60]:
## 1-d array:

a

array([0, 2, 4, 6, 8])

In [61]:
a[3]

6

In [62]:
a[-2]

6

In [63]:
a[2:]

array([4, 6, 8])

In [64]:
a[1:3]

array([2, 4])

In [70]:
## 2-d array:

b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [66]:
b[0]

array([1, 2, 3, 4])

In [67]:
b[-1]

array([5, 6, 7, 8])

In [69]:
b[0,-1]  ### row_index_value,element_index_value

4

In [71]:
b[1,2]

7

In [72]:
b[:,2]

array([3, 7])

In [73]:
b[0,2:]

array([3, 4])

In [74]:
b[:,2:]

array([[3, 4],
       [7, 8]])

In [75]:
#### 3-d array:

c

array([[[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[5, 6, 7, 8],
        [9, 8, 7, 6]]])

In [76]:
c[0]

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [77]:
c[1]

array([[5, 6, 7, 8],
       [9, 8, 7, 6]])

In [78]:
c[0,0]

array([1, 2, 3, 4])

In [80]:
c[0,0,-1]   ### 2d_index_value,row_index_value,element_index_value

4

In [81]:
c[:,0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [82]:
c[:,:,2:]

array([[[3, 4],
        [3, 4]],

       [[7, 8],
        [7, 6]]])

In [85]:
b = np.arange(0,10,3)
b 

array([0, 3, 6, 9])

In [87]:
b = np.append(b,[1,2])

In [88]:
b

array([0, 3, 6, 9, 1, 2])